name: Debug - Build and Test with Bazel
permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: windows-2019
#     env:
#       BAZEL_VC_FULL_VERSION: 14.35.32215

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Download dependencies
        run: python3 utils/git-sync-deps
        
      - name: 'list vc tools 1'
        run: |
          get-childitem -Path 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC'
          get-content 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.v143.default.props'
          write-host "---"
          get-content 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.props'
          get-childitem 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\'
          
#       - name: install workloads
#         run: |
#           Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
#           $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
#           $componentsToAdd = @(
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ARM",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ARM.Spectre",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ARM64",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ARM64.Spectre",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.x86.x64",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.x86.x64.Spectre",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ATL",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ATL.Spectre",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ATL.ARM",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ATL.ARM.Spectre",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ATL.ARM64",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.ATL.ARM64.Spectre",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.MFC",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.MFC.Spectre",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.MFC.ARM",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.MFC.ARM.Spectre",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.MFC.ARM64",
#               "Microsoft.VisualStudio.Component.VC.14.36.17.6.MFC.ARM64.Spectre"
#           )
#           [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
#           $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
#           $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
#           if ($process.ExitCode -eq 0)
#           {
#               Write-Host "components have been successfully added"
#           }
#           else
#           {
#               Write-Host "components were not installed"
#               exit 1
#           }
          
      - name: 'list vc tools 2'
        run: |
          get-childitem -Path 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
          
      - name: Mount Bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.bazel/cache
          key: bazel-cache-${{ runner.os }}         

      - name: Build All (Windows)
        run: bazel --output_user_root=~/.bazel/cache build //...
      - name: Test All (Windows)
        run: bazel --output_user_root=~/.bazel/cache test //...
